### ISSUE TITLE
Usage of `[weak self]` inside Promise's body

### ISSUE THREAD

**Issue by Ruckt** [malcommac/Hydra#58]
How do you use '[weak self]' in the then portion of the promise?  Or do you not need to?

**Comment by tskippervold** [comment]
@Ruckt its for preventing a retain cycle. Take this slightly modified example from the readme:

`getImage(url).then(.main, { image in
	self.myImageView.image = image
})`

This will cause a retain cycle, since you are capturing `self` inside a completion block, thus resulting in `self` never will be deallocated, since you are holding a strong reference to it for a unknown lifecycle.

So to fix this, you can do something like this:

`getImage(url).then(.main, { [weak self] image in
	self?.myImageView.image = image
})`

or my personal way of doing it:

`getImage(url).then(.main, { [weak self] image in
        guard let _self = self else {
                return
        }
	_self.myImageView.image = image
})`
